Repository c1one-team/c1one, pull requests merged in 2025-06, with the labels that each got.

#7 [Chore] user 패키지 및 엔티티 생성
  .gitignore
  src/main/java/uniqram/c1one/user/entity/Users.java
  src/main/java/uniqram/c1one/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: setting

#8 테이블 공통사항 BaseEntity 상속(Users 클래스 코드 변경)
  src/main/java/uniqram/c1one/user/entity/Users.java
Labels: refactor

#19 [Feat] 게시글(Post) 및 미디어(PostMedia) 엔티티 생성
  src/main/java/uniqram/c1one/comment/entity/Comment.java
  src/main/java/uniqram/c1one/post/controller/.gitkeep
  src/main/java/uniqram/c1one/post/dto/.gitkeep
  src/main/java/uniqram/c1one/post/entity/Post.java
  src/main/java/uniqram/c1one/post/entity/PostMedia.java
  src/main/java/uniqram/c1one/post/repository/.gitkeep
  src/main/java/uniqram/c1one/post/service/.gitkeep
Labels: feature

#21 [Feat] 프로필(profile) 설계 및 기본 엔티티 구현
  src/main/java/uniqram/c1one/profile/entity/Profile.java
  src/main/java/uniqram/c1one/profile/repository/ProfileRepository.java
Labels: feature

#40 [Feat] Role 기반 접근 제어 기능 구현
  src/main/java/uniqram/c1one/auth/controller/RoleTestController.java
  src/main/java/uniqram/c1one/global/config/SecurityConfig.java
Labels: feature

#35 [Feat] 게시글 등록 기능 구현
  src/main/java/uniqram/c1one/global/config/SecurityConfig.java
  src/main/java/uniqram/c1one/post/controller/.gitkeep
  src/main/java/uniqram/c1one/post/controller/PostController.java
  src/main/java/uniqram/c1one/post/dto/.gitkeep
  src/main/java/uniqram/c1one/post/dto/PostRequest.java
  src/main/java/uniqram/c1one/post/dto/PostResponse.java
  src/main/java/uniqram/c1one/post/entity/Post.java
  src/main/java/uniqram/c1one/post/exception/PostErrorCode.java
  src/main/java/uniqram/c1one/post/exception/PostException.java
  src/main/java/uniqram/c1one/post/exception/PostSuccessCode.java
  src/main/java/uniqram/c1one/post/repository/.gitkeep
  src/main/java/uniqram/c1one/post/repository/PostRepository.java
  src/main/java/uniqram/c1one/post/service/.gitkeep
  src/main/java/uniqram/c1one/post/service/PostService.java
Labels: feature

#37 [Feat] PostLike 엔티티 생성
  src/main/java/uniqram/c1one/comment/entity/CommentLike.java
  src/main/java/uniqram/c1one/post/entity/Post.java
  src/main/java/uniqram/c1one/post/entity/PostLike.java
Labels: feature

#46 [Feat] JWT 토큰 생성 및 검증, JWT 정보 파싱
  src/main/java/uniqram/c1one/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/uniqram/c1one/auth/jwt/JwtTokenProvider.java
  src/main/java/uniqram/c1one/search/repository/SearchHistoryRepositoryImpl.java
  src/main/resources/application.yml
  src/test/java/uniqram/c1one/auth/jwt/JwtTokenProviderTest.java
Labels: feature

#42 [Refactor] Post Entity 코드 개선
  src/main/java/uniqram/c1one/post/entity/Post.java
Labels: refactor

#50 [Feat] 시큐리티 설정 클래스 추가
  src/main/java/uniqram/c1one/auth/config/SecurityConfig.java
Labels: feature

#54 [Refactor] Setter 제거 및 불변 구조 리팩토링
  src/main/java/uniqram/c1one/auth/controller/AuthController.java
  src/main/java/uniqram/c1one/auth/dto/SignupRequest.java
Labels: refactor

#56 [Fix] SecurityConfig 빈 이름 충돌
  src/main/java/uniqram/c1one/auth/config/SecurityConfig.java
  src/main/java/uniqram/c1one/global/config/SecurityConfig.java
Labels: bug

#64 [Feat] 북마크 토글 기능 구현
  src/main/java/uniqram/c1one/post/controller/BookmarkController.java
  src/main/java/uniqram/c1one/post/dto/BookmarkRequest.java
  src/main/java/uniqram/c1one/post/entity/Bookmark.java
  src/main/java/uniqram/c1one/post/exception/BookmarkSuccessCode.java
  src/main/java/uniqram/c1one/post/repository/BookmarkRepository.java
  src/main/java/uniqram/c1one/post/service/BookmarkService.java
Labels: feature

#63 [Feat] 게시글 삭제 api 구현
  src/main/java/uniqram/c1one/post/controller/BookmarkController.java
  src/main/java/uniqram/c1one/post/controller/PostController.java
  src/main/java/uniqram/c1one/post/dto/BookmarkRequest.java
  src/main/java/uniqram/c1one/post/entity/Bookmark.java
  src/main/java/uniqram/c1one/post/exception/BookmarkSuccessCode.java
  src/main/java/uniqram/c1one/post/repository/BookmarkRepository.java
  src/main/java/uniqram/c1one/post/service/BookmarkService.java
  src/main/java/uniqram/c1one/post/service/PostService.java
Labels: feature

#61 [Feat] 게시글 수정 api 구현
  src/main/java/uniqram/c1one/post/controller/BookmarkController.java
  src/main/java/uniqram/c1one/post/controller/PostController.java
  src/main/java/uniqram/c1one/post/dto/BookmarkRequest.java
  src/main/java/uniqram/c1one/post/dto/PostCreateRequest.java
  src/main/java/uniqram/c1one/post/dto/PostUpdateRequest.java
  src/main/java/uniqram/c1one/post/entity/Bookmark.java
  src/main/java/uniqram/c1one/post/entity/Post.java
  src/main/java/uniqram/c1one/post/exception/BookmarkSuccessCode.java
  src/main/java/uniqram/c1one/post/exception/PostErrorCode.java
  src/main/java/uniqram/c1one/post/repository/BookmarkRepository.java
  src/main/java/uniqram/c1one/post/service/BookmarkService.java
  src/main/java/uniqram/c1one/post/service/PostService.java
Labels: feature

#74 [Feat] [Refactor] UserDetails 구현체 구현 및 Service 구현, auth 관련 클래스 코드 수정
  src/main/java/uniqram/c1one/auth/controller/AuthController.java
  src/main/java/uniqram/c1one/auth/dto/JwtToken.java
  src/main/java/uniqram/c1one/auth/dto/SigninRequest.java
  src/main/java/uniqram/c1one/auth/service/AuthService.java
  src/main/java/uniqram/c1one/global/config/SecurityConfig.java
  src/main/java/uniqram/c1one/security/adapter/CustomUserDetails.java
  src/main/java/uniqram/c1one/security/adapter/CustomUserDetailsService.java
  src/main/java/uniqram/c1one/security/jwt/JwtAuthenticationFilter.java
  src/main/java/uniqram/c1one/security/jwt/JwtTokenProvider.java
  src/main/java/uniqram/c1one/user/entity/Users.java
  src/test/java/uniqram/c1one/auth/jwt/JwtTokenProviderTest.java
Labels: feature, refactor

#71 [Feat] 댓글 생성/조회 기능 구현
  src/main/java/uniqram/c1one/comment/controller/CommentController.java
  src/main/java/uniqram/c1one/comment/service/CommentService.java
Labels: feature

#77 [Feat] 댓글 수정/삭제 기능 개발 및 Comment 관련 상태 코드 추가
  src/main/java/uniqram/c1one/comment/controller/CommentController.java
  src/main/java/uniqram/c1one/comment/dto/CommentCreateRequest.java
  src/main/java/uniqram/c1one/comment/dto/CommentResponse.java
  src/main/java/uniqram/c1one/comment/dto/CommentUpdateRequest.java
  src/main/java/uniqram/c1one/comment/exception/CommentErrorCode.java
  src/main/java/uniqram/c1one/comment/exception/CommentException.java
  src/main/java/uniqram/c1one/comment/exception/CommentSuccessCode.java
  src/main/java/uniqram/c1one/comment/service/CommentService.java
Labels: feature

#78 [Feat] Admin 회원가입 API 추가
  src/main/java/uniqram/c1one/auth/controller/AdminAuthController.java
  src/main/java/uniqram/c1one/auth/service/AuthService.java
  src/main/java/uniqram/c1one/global/config/SecurityConfig.java
Labels: feature

#87 [Feat][Fix] toggle 방식의 댓글/게시물 좋아요 기능 개발 및 테스트 코드 추가
  src/main/java/uniqram/c1one/comment/controller/CommentController.java
  src/main/java/uniqram/c1one/comment/dto/CommentLikeResponse.java
  src/main/java/uniqram/c1one/comment/dto/CommentResponse.java
  src/main/java/uniqram/c1one/comment/entity/Comment.java
  src/main/java/uniqram/c1one/comment/repository/CommentLikeRepository.java
  src/main/java/uniqram/c1one/comment/service/CommentLikeService.java
  src/main/java/uniqram/c1one/comment/service/CommentService.java
  src/main/java/uniqram/c1one/post/controller/PostController.java
  src/main/java/uniqram/c1one/post/dto/HomePostResponse.java
  src/main/java/uniqram/c1one/post/dto/PostLikeResponse.java
  src/main/java/uniqram/c1one/post/entity/Post.java
  src/main/java/uniqram/c1one/post/repository/PostLikeRepository.java
  src/main/java/uniqram/c1one/post/service/PostLikeService.java
  src/main/java/uniqram/c1one/post/service/PostService.java
  src/test/java/uniqram/c1one/comment/service/CommentLikeServiceTest.java
  src/test/java/uniqram/c1one/comment/service/CommentServiceTest.java
Labels: feature

#91 [Refactor] CommentService의 orElseThrow() 구문 변경
  src/main/java/uniqram/c1one/comment/exception/CommentErrorCode.java
  src/main/java/uniqram/c1one/comment/service/CommentService.java
Labels: refactor

#92 [Refactor] 홈 화면 조회 API N+1 문제 개선
  src/main/java/uniqram/c1one/post/controller/PostController.java
  src/main/java/uniqram/c1one/post/dto/CommentCountDto.java
  src/main/java/uniqram/c1one/post/dto/CommentDto.java
  src/main/java/uniqram/c1one/post/dto/HomePostResponse.java
  src/main/java/uniqram/c1one/post/dto/LikeCountDto.java
  src/main/java/uniqram/c1one/post/dto/LikeUserDto.java
  src/main/java/uniqram/c1one/post/dto/PostResponse.java
  src/main/java/uniqram/c1one/post/repository/PostLikeRepository.java
  src/main/java/uniqram/c1one/post/repository/PostMediaRepository.java
  src/main/java/uniqram/c1one/post/service/PostService.java
Labels: refactor

#95 [Feat] 팔로우 기능 설계 및 구현
  src/main/java/uniqram/c1one/follow/controller/FollowController.java
  src/main/java/uniqram/c1one/follow/dto/FollowRequestDto.java
  src/main/java/uniqram/c1one/follow/entity/Follow.java
  src/main/java/uniqram/c1one/follow/exception/FollowErrorCode.java
  src/main/java/uniqram/c1one/follow/exception/FollowException.java
  src/main/java/uniqram/c1one/follow/repository/FollowRepository.java
  src/main/java/uniqram/c1one/follow/service/FollowService.java
  src/test/java/uniqram/c1one/follow/service/FollowServiceTest.java
Labels: feature

#100 [Refactor] 회원가입에서 email 필드 제거 및 관련 로직 정리
  src/main/java/uniqram/c1one/auth/dto/SignupRequest.java
  src/main/java/uniqram/c1one/user/entity/Users.java
  src/test/java/uniqram/c1one/auth/service/AuthServiceTest.java
  src/test/java/uniqram/c1one/profile/service/ProfileServiceTest.java
Labels: refactor

#99 [Refactor] CommentController 분리
  src/main/java/uniqram/c1one/comment/controller/CommentController.java
  src/main/java/uniqram/c1one/comment/controller/PostCommentController.java
  src/main/java/uniqram/c1one/comment/dto/CommentCreateRequest.java
  src/main/java/uniqram/c1one/comment/service/CommentService.java
Labels: refactor
