Repository c1one-team/c1one, pull requests merged in 2025-07, with the labels that each got.

#114 [Refactor] 게시글 및 북마크 API @AuthenticationPrincipal 기반으로 리팩터링
  src/main/java/uniqram/c1one/post/controller/BookmarkController.java
  src/main/java/uniqram/c1one/post/controller/PostController.java
  src/main/java/uniqram/c1one/post/dto/BookmarkRequest.java
  src/main/java/uniqram/c1one/security/adapter/CustomUserDetails.java
Labels: refactor

#124 [Fix] AuthControllerTest 에러 해결
  src/test/java/uniqram/c1one/auth/controller/AuthControllerTest.java
Labels: bug

#127 [Refactor] Comment 도메인 @AuthenticationPrincipal 변경
  src/main/java/uniqram/c1one/comment/controller/CommentController.java
  src/main/java/uniqram/c1one/comment/controller/PostCommentController.java
  src/main/java/uniqram/c1one/comment/dto/CommentCreateRequest.java
  src/main/java/uniqram/c1one/comment/service/CommentService.java
Labels: refactor

#129 [Refactor] 토큰 만료 시간 변경
  src/main/java/uniqram/c1one/auth/controller/AuthController.java
  src/main/java/uniqram/c1one/security/jwt/JwtTokenProvider.java
Labels: refactor

#130 [Refactor] 게시물 수정 요청 DTO의 userId 필드 제거 및 이미지 필수 로직 개선
  src/main/java/uniqram/c1one/post/dto/PostCreateRequest.java
  src/main/java/uniqram/c1one/post/dto/PostUpdateRequest.java
  src/main/java/uniqram/c1one/post/service/PostService.java
Labels: refactor

#131 [Refactor] 댓글/게시글 좋아요 증감처리 및 조회 기능 redis 적용
  src/main/java/uniqram/c1one/comment/repository/CommentLikeRepository.java
  src/main/java/uniqram/c1one/comment/service/CommentLikeService.java
  src/main/java/uniqram/c1one/comment/service/CommentService.java
  src/main/java/uniqram/c1one/global/service/LikeCountService.java
  src/main/java/uniqram/c1one/post/repository/PostLikeRepository.java
  src/main/java/uniqram/c1one/post/service/PostLikeService.java
  src/main/resources/application.yml
Labels: refactor

#139 [Refactor] 중복된 AdminAuthController 파일 삭제
  src/main/java/uniqram/c1one/auth/controller/AdminAuthController.java
Labels: refactor

#142 [Feat] Redis 설정 패키지 추가
  src/main/java/uniqram/c1one/redis/config/JacksonConfig.java
  src/main/java/uniqram/c1one/redis/config/RedisConfig.java
  src/main/java/uniqram/c1one/redis/controller/AdminController.java
  src/main/java/uniqram/c1one/redis/listener/AuthenticationEventListener.java
  src/main/java/uniqram/c1one/redis/model/ActiveUser.java
  src/main/java/uniqram/c1one/redis/model/UserRedisDto.java
  src/main/java/uniqram/c1one/redis/model/UserStatus.java
  src/main/java/uniqram/c1one/redis/service/ActiveUserService.java
Labels: feature

#144 [Refactor] Follow @AuthenticationPrincipal 방식 리펙토링
  src/main/java/uniqram/c1one/follow/controller/FollowController.java
  src/main/java/uniqram/c1one/follow/dto/FollowRequestDto.java
Labels: refactor

#146 [Refactor] Profile @AuthenticationPrincipal 방식 리펙토링
  src/main/java/uniqram/c1one/profile/controller/ProfileController.java
  src/main/java/uniqram/c1one/profile/service/ProfileService.java
Labels: refactor

#147 [Fix] 댓글 조회 시 N+1 문제 해결
  build.gradle
  src/main/generated/uniqram/c1one/comment/entity/QComment.java
  src/main/generated/uniqram/c1one/comment/entity/QCommentLike.java
  src/main/generated/uniqram/c1one/follow/entity/QFollow.java
  src/main/generated/uniqram/c1one/global/QBaseEntity.java
  src/main/generated/uniqram/c1one/post/entity/QBookmark.java
  src/main/generated/uniqram/c1one/post/entity/QPost.java
  src/main/generated/uniqram/c1one/post/entity/QPostLike.java
  src/main/generated/uniqram/c1one/post/entity/QPostMedia.java
  src/main/generated/uniqram/c1one/profile/entity/QProfile.java
  src/main/generated/uniqram/c1one/search/entity/QSearchHistory.java
  src/main/generated/uniqram/c1one/user/entity/QUsers.java
  src/main/java/uniqram/c1one/comment/controller/PostCommentController.java
  src/main/java/uniqram/c1one/comment/dto/CommentListResponse.java
  src/main/java/uniqram/c1one/comment/entity/Comment.java
  src/main/java/uniqram/c1one/comment/repository/CommentRepository.java
  src/main/java/uniqram/c1one/comment/repository/CommentRepositoryCustom.java
  src/main/java/uniqram/c1one/comment/repository/CommentRepositoryImpl.java
  src/main/java/uniqram/c1one/comment/service/CommentService.java
  src/main/java/uniqram/c1one/global/config/QuerydslConfig.java
  src/main/java/uniqram/c1one/post/dto/PostDetailResponse.java
  src/main/java/uniqram/c1one/post/service/PostService.java
  src/main/java/uniqram/c1one/user/entity/Users.java
Labels: bug

#149 [Test] 테스트 케이스 주석 처리
  src/test/java/uniqram/c1one/comment/service/CommentLikeServiceTest.java
  src/test/java/uniqram/c1one/post/PostServiceTest.java
Labels: deploy

#150 [Refactor] Redis 기반 접속 중 유저 조회 로직 리팩토링
  src/main/java/uniqram/c1one/admin/dto/DashboardResponse.java
  src/main/java/uniqram/c1one/admin/dto/UserSummaryResponse.java
  src/main/java/uniqram/c1one/admin/service/AdminDashboardService.java
  src/main/java/uniqram/c1one/admin/service/AdminUserService.java
  src/main/java/uniqram/c1one/redis/config/RedisConfig.java
  src/main/java/uniqram/c1one/redis/service/ActiveUserService.java
Labels: refactor

#157 [Fix] PostDetailResponse comments 타입 불일치 에러 수정
  src/main/java/uniqram/c1one/post/dto/CommentCountDto.java
  src/main/java/uniqram/c1one/post/dto/PostDetailResponse.java
  src/main/java/uniqram/c1one/post/service/PostService.java
  src/test/java/uniqram/c1one/post/PostServiceTest.java
Labels: bug

#160 [Feat] DM 관련 도메인 개발
  src/main/java/uniqram/c1one/dm/entity/ChatMessage.java
  src/main/java/uniqram/c1one/dm/entity/ChatRoom.java
  src/main/java/uniqram/c1one/dm/entity/ChatRoomMember.java
  src/main/java/uniqram/c1one/dm/entity/ChatRoomType.java
  src/main/java/uniqram/c1one/dm/repository/ChatMessageRepository.java
  src/main/java/uniqram/c1one/dm/repository/ChatRoomMemberRepository.java
  src/main/java/uniqram/c1one/dm/repository/ChatRoomRepository.java
Labels: feature

#163 [Feat] [Refactor] refresh token 값을 DB에 저장하고 refresh token 생성값 변경
  .gitignore
  src/main/java/uniqram/c1one/auth/controller/AuthController.java
  src/main/java/uniqram/c1one/security/jwt/JwtTokenProvider.java
  src/main/java/uniqram/c1one/security/jwt/entity/RefreshToken.java
  src/main/java/uniqram/c1one/security/jwt/repository/RefreshTokenRepository.java
Labels: feature, refactor

#159 [Feat] 홈화면 팔로잉된 사람들의 게시물만 조회 기능 추가
  src/main/java/uniqram/c1one/follow/repository/FollowRepository.java
  src/main/java/uniqram/c1one/post/controller/PostController.java
  src/main/java/uniqram/c1one/post/repository/PostMediaRepository.java
  src/main/java/uniqram/c1one/post/repository/PostRepository.java
  src/main/java/uniqram/c1one/post/service/PostService.java
  src/test/java/uniqram/c1one/post/PostServiceTest.java
Labels: feature

#166 [Feat] 홈 추천 게시물 조회 기능 구현
  src/main/java/uniqram/c1one/post/controller/PostController.java
  src/main/java/uniqram/c1one/post/repository/PostRepository.java
  src/main/java/uniqram/c1one/post/service/PostService.java
  src/test/java/uniqram/c1one/post/PostServiceTest.java
Labels: feature

#168 [Refactor] 관리자 대시보드 좋아요 수 Redis 기반 조회로 변경
  src/main/java/uniqram/c1one/admin/service/AdminDashboardService.java
Labels: refactor

#176 [Refactor] 대시보드에 실시간 접속자 수 연동 및 접속자 관리 기능 개선
  src/main/java/uniqram/c1one/security/jwt/JwtAuthenticationFilter.java
Labels: refactor

#180 [Refactor] Comment, DM 도메인 컨트롤러 URL 변경
  src/main/java/uniqram/c1one/comment/controller/CommentController.java
  src/main/java/uniqram/c1one/comment/controller/PostCommentController.java
  src/main/java/uniqram/c1one/dm/controller/ChatRoomController.java
Labels: refactor

#187 [Refactor] post 도메인 api 경로 변경
  src/main/java/uniqram/c1one/post/controller/BookmarkController.java
  src/main/java/uniqram/c1one/post/controller/PostController.java
Labels: refactor

#188 [Feat] 채팅 메세지 수정/삭제 및 읽음 처리 기능 추가
  src/main/java/uniqram/c1one/dm/controller/ChatRoomController.java
  src/main/java/uniqram/c1one/dm/dto/ChatMessageResponse.java
  src/main/java/uniqram/c1one/dm/entity/ChatMessage.java
  src/main/java/uniqram/c1one/dm/exception/DmErrorCode.java
  src/main/java/uniqram/c1one/dm/service/ChatMessageService.java
Labels: feature

#185 [Refactor] redis 패키지에서 안쓰이는 클래스, 메서드 삭제
  .DS_Store
  src/main/java/uniqram/c1one/redis/model/UserRedisDto.java
  src/main/java/uniqram/c1one/redis/model/UserStatus.java
  src/main/java/uniqram/c1one/redis/service/ActiveUserService.java
Labels: refactor

#191 [Feat] Redis Pub/Sub 및 WebSocket 연동 기능 추가
  build.gradle
  src/main/java/uniqram/c1one/dm/dto/ChatMessageDto.java
  src/main/java/uniqram/c1one/redis/config/RedisConfig.java
  src/main/java/uniqram/c1one/redis/listener/ChatMessageSubscriber.java
  src/main/java/uniqram/c1one/redis/service/ChatMessagePublisher.java
  src/main/java/uniqram/c1one/websocket/config/WebSocketConfig.java
  src/main/java/uniqram/c1one/websocket/controller/ChatWebSocketController.java
Labels: feature

#189 [Feat] 프로필 이미지 업로드 추가
  src/main/java/uniqram/c1one/profile/controller/ProfileController.java
  src/main/java/uniqram/c1one/profile/dto/ProfileResponseDto.java
  src/main/java/uniqram/c1one/profile/service/ProfileService.java
  src/test/java/uniqram/c1one/profile/service/ProfileServiceTest.java
Labels: feature

#199 [Refactor] 블랙리스트 유저 관련 백엔드 로직 개선
  src/main/java/uniqram/c1one/admin/service/AdminDashboardService.java
  src/main/java/uniqram/c1one/auth/controller/AuthController.java
  src/main/java/uniqram/c1one/security/adapter/CustomUserDetails.java
  src/main/java/uniqram/c1one/user/repository/UserRepository.java
Labels: refactor

#205 [Refactor] 게시물 수정 API 로직 변경
  src/main/java/uniqram/c1one/post/dto/PostUpdateRequest.java
  src/main/java/uniqram/c1one/post/exception/PostErrorCode.java
  src/main/java/uniqram/c1one/post/service/PostService.java
  src/test/java/uniqram/c1one/post/PostServiceTest.java
Labels: refactor

#211 [Feat] dto에 bookmarkedByMe 추가
  src/main/java/uniqram/c1one/post/dto/HomePostResponse.java
  src/main/java/uniqram/c1one/post/dto/PostDetailResponse.java
  src/main/java/uniqram/c1one/post/repository/BookmarkRepository.java
  src/main/java/uniqram/c1one/post/service/PostService.java
  src/test/java/uniqram/c1one/post/PostServiceTest.java
Labels: feature

#230 [Refactor] JwtTokenProvider 생성자에 RedisTemplate 주입 추가
  src/main/java/uniqram/c1one/security/jwt/JwtTokenProvider.java
Labels: refactor
